db_file: "bot.db"

bot_url: "https://t.me/AnekPocketBot"

messages:
  responses:
    start: "Привет! Чтобы пользоваться данным ботом, тебе необходимо дать доступ к своему аккаунту по этой ссылочке: \n%s"
    already_authorized: "Ты уже авторизирован! Жду твои ссылочки; )"
    saved_successfully: "Ссылка успешно сохранена!"
    unknown_command: "Я не знаю такой команды"
  errors:
    default: "Произошла неизвестная ошибка"
    invalidURL: "Ссылка невалидна"
    unauthorized: "Для сохранения ссылок, нужно авторизоваться (команда /start)"
    unable_to_save: "Не удалось сохранить ссылку, попробуй еще раз попозже"